### ISSUE TITLE
TreeWalker - com/github/sevntu/checkstyle/Utils

### ISSUE THREAD

**Issue by balizeiro** [sevntu-checkstyle/sevntu.checkstyle#347] opened 2015-05-25 15:17 UTC
After updating to version 1.13.0 I started getting this exception on all my java files:
    TreeWalker: Got an exception - com/github/sevntu/checkstyle/Utils

**Comment by romani** [comment] 2015-05-25 16:33
is it after activation of PublicReferenceToPrivateTypeCheck ? https://github.com/sevntu-checkstyle/sevntu.checkstyle/issues/343

can you narrow down to check that cause that

**Comment by balizeiro** [comment] 2015-05-26 10:08
Just checked it now, and if I disable PublicReferenceToPrivateTypeCheck it stops giving that error

**Comment by romani** [comment] 2015-05-26 14:05
Duplicate of #343

**Closed by romani** 2015-05-26 14:05 UTC

**Comment by romani** [comment] 2015-06-07 06:13
fixed and relesed as 1.13.1 - http://sevntu-checkstyle.github.io/sevntu.checkstyle/#1.13.1
