### ISSUE TITLE
False positive in SimpleAccessorNameNotation check

### ISSUE THREAD

**Issue by mkordas** [sevntu-checkstyle/sevntu.checkstyle#369] opened 2015-08-03 07:35 UTC
SimpleAccessorNameNotation check reports the following violation when getter is provided for private static final constant:
```java
class FalsePositive {
    private static final String MY_CONSTANT = "";

    String getMyConstant() { // violation here, wrong getter name
        return MY_CONSTANT;
    }
}
```

**Comment by valfirst** [comment] 2016-01-13 08:25
+1. I faced with the same issue

**Comment by romani** [comment] 2016-01-13 13:52
duplicate of #166

**Closed by romani** 2016-01-13 13:52 UTC
