### ISSUE TITLE
Update maven build configuration for 'sevntu-checks' module to run Checkstyle on the sources

### ISSUE THREAD

**Issue by rdiachenko** [sevntu-checkstyle/sevntu.checkstyle#309] opened 2015-02-06 20:30 UTC
When maven build is executed Checkstyle checks should be run on the `sevntu-checks` sources like it is done in the main project.

This will allow us:
1. To automate code format validation
2. To resolve Checkstyle violations on the earlier stage (even before pull request)
3. To simplify movement checks into the main project

**Comment by damianszczepanik** [comment] 2015-03-01 10:43
Duplicate of #310 ?

**Comment by romani** [comment] 2015-03-01 15:21
Looks like duplicates and created at the same day. @rdiachenko , please confirm your proposals.

**Comment by rnveach** [comment] 2016-12-03 17:35
Closing as a duplicate of #310 which is finished

**Closed by rnveach** 2016-12-03 17:35 UTC
