### ISSUE TITLE
Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.17:check 

### ISSUE THREAD

**Issue by sreekar426** [sevntu-checkstyle/sevntu.checkstyle#593] opened 2017-06-16 13:12 UTC
Hi i want to create my own customized sonar rules and i want to implement it on my project,
so i got the source from sevntu.checkstyle .

when i tried to compile it on my machine which is win10 i am getting compilation error here is the log  :-

````
D:\Softwares\sevntu.checkstyle-master\sevntu.checkstyle-master\sevntu-checks>mvn clean install
[INFO] Scanning for projects...
[INFO] Inspecting build with total of 1 modules...
[INFO] Installing Nexus Staging features:
[INFO]   ... total of 1 executions of maven-deploy-plugin replaced with nexus-staging-maven-plugin
[INFO]
[INFO] Using the builder org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder with a thread count of 1
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building sevntu-checks 1.24.0
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ sevntu-checks ---
[INFO] Deleting D:\Softwares\sevntu.checkstyle-master\sevntu.checkstyle-master\sevntu-checks\target
[INFO]
[INFO] --- maven-enforcer-plugin:1.2:enforce (enforce-maven) @ sevntu-checks ---
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ sevntu-checks ---
[INFO] Using 'iso-8859-1' encoding to copy filtered resources.
[INFO] Copying 6 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.3:compile (default-compile) @ sevntu-checks ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 60 source files to D:\Softwares\sevntu.checkstyle-master\sevntu.checkstyle-master\sevntu-checks\target\classes
[INFO] /D:/Softwares/sevntu.checkstyle-master/sevntu.checkstyle-master/sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/design/NestedSwitchCheck.java: Some input files use or override a deprecated API.
[INFO] /D:/Softwares/sevntu.checkstyle-master/sevntu.checkstyle-master/sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/design/NestedSwitchCheck.java: Recompile with -Xlint:deprecation for details.
[INFO]
[INFO] --- maven-checkstyle-plugin:2.17:check (default) @ sevntu-checks ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.511 s
[INFO] Finished at: 2017-06-16T18:00:08+05:30
[INFO] Final Memory: 30M/358M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.17:check (default) on project sevntu-checks: Failed during checkstyle configuration: cannot initialize module BeforeExecutionExclusionFileFilter - Unable to instantiate 'BeforeExecutionExclusionFileFilter' class, it is also not possible to instantiate it as com.puppycrawl.tools.checkstyle.checks.annotation.BeforeExecutionExclusionFileFilter, com.puppycrawl.tools.checkstyle.checks.blocks.BeforeExecutionExclusionFileFilter, com.puppycrawl.tools.checkstyle.checks.coding.BeforeExecutionExclusionFileFilter, com.puppycrawl.tools.checkstyle.checks.design.BeforeExecutionExclusionFileFilter, com.puppycrawl.tools.checkstyle.checks.header.BeforeExecutionExclusionFileFilter, com.puppycrawl.tools.checkstyle.checks.imports.BeforeExecutionExclusionFileFilter, com.puppycrawl.tools.checkstyle.checks.indentation.BeforeExecutionExclusionFileFilter, com.puppycrawl.tools.checkstyle.checks.javadoc.BeforeExecutionExclusionFileFilter, com.puppycrawl.tools.checkstyle.checks.metrics.BeforeExecutionExclusionFileFilter, com.puppycrawl.tools.checkstyle.checks.modifier.BeforeExecutionExclusionFileFilter, com.puppycrawl.tools.checkstyle.checks.naming.BeforeExecutionExclusionFileFilter, com.puppycrawl.tools.checkstyle.checks.regexp.BeforeExecutionExclusionFileFilter, com.puppycrawl.tools.checkstyle.checks.sizes.BeforeExecutionExclusionFileFilter, com.puppycrawl.tools.checkstyle.checks.whitespace.BeforeExecutionExclusionFileFilter, com.puppycrawl.tools.checkstyle.checks.BeforeExecutionExclusionFileFilter, com.puppycrawl.tools.checkstyle.filters.BeforeExecutionExclusionFileFilter, com.puppycrawl.tools.checkstyle.BeforeExecutionExclusionFileFilter, BeforeExecutionExclusionFileFilterCheck, com.puppycrawl.tools.checkstyle.checks.annotation.BeforeExecutionExclusionFileFilterCheck, com.puppycrawl.tools.checkstyle.checks.blocks.BeforeExecutionExclusionFileFilterCheck, com.puppycrawl.tools.checkstyle.checks.coding.BeforeExecutionExclusionFileFilterCheck, com.puppycrawl.tools.checkstyle.checks.design.BeforeExecutionExclusionFileFilterCheck, com.puppycrawl.tools.checkstyle.checks.header.BeforeExecutionExclusionFileFilterCheck, com.puppycrawl.tools.checkstyle.checks.imports.BeforeExecutionExclusionFileFilterCheck, com.puppycrawl.tools.checkstyle.checks.indentation.BeforeExecutionExclusionFileFilterCheck, com.puppycrawl.tools.checkstyle.checks.javadoc.BeforeExecutionExclusionFileFilterCheck, com.puppycrawl.tools.checkstyle.checks.metrics.BeforeExecutionExclusionFileFilterCheck, com.puppycrawl.tools.checkstyle.checks.modifier.BeforeExecutionExclusionFileFilterCheck, com.puppycrawl.tools.checkstyle.checks.naming.BeforeExecutionExclusionFileFilterCheck, com.puppycrawl.tools.checkstyle.checks.regexp.BeforeExecutionExclusionFileFilterCheck, com.puppycrawl.tools.checkstyle.checks.sizes.BeforeExecutionExclusionFileFilterCheck, com.puppycrawl.tools.checkstyle.checks.whitespace.BeforeExecutionExclusionFileFilterCheck, com.puppycrawl.tools.checkstyle.checks.BeforeExecutionExclusionFileFilterCheck, com.puppycrawl.tools.checkstyle.filters.BeforeExecutionExclusionFileFilterCheck, com.puppycrawl.tools.checkstyle.BeforeExecutionExclusionFileFilterCheck. Please recheck that class name is specified as canonical name or read how to configure short name usage http://checkstyle.sourceforge.net/config.html#Packages. Please also recheck that provided ClassLoader to Checker is configured correctly. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
D:\Softwares\sevntu.checkstyle-master\sevntu.checkstyle-master\sevntu-checks>
````

can you please let me some solution to over come this ERROR or else is there any other project so that i can create my own rules and deploy it in sonar server then can be able to use in my project.

Thanks,
Sreekar C

**Comment by rnveach** [comment] 2017-06-16 13:44
@sreekar426 I am unable to reproduce the issue when I run `mvn clean install`.
[Travis also runs the same command](https://travis-ci.org/sevntu-checkstyle/sevntu.checkstyle/jobs/241637733#L153) and passed without failure.

Can you verify you are on the latest version of master with no modifications or unstaged changes?

**Comment by romani** [comment] 2017-06-16 15:02
@sreekar426 , please move your sources to github or any other public repo to let us look at your configuration

**Comment by rnveach** [comment] 2022-10-14 21:35
I am closing this as there has been no reply

**Closed by rnveach** 2022-10-14 21:35 UTC
