### ISSUE TITLE
New check: Jsr305Annotations

### ISSUE THREAD

**Issue by mbert** [sevntu-checkstyle/sevntu.checkstyle#734] opened 2019-04-02 12:55 UTC
The _Jsr305_ annotations (annotations for software defect detection) contain a subset of "nullness" annotations that can be used to mark parameters as possibly null (`@Nullable`) or always non-null (`@Nonnull`), function return values as to be checked for null (`@CheckForNull`) or always non-null (`@Nonnull`) including defaults on class level (`@ParametersAreNonnullByDefault`, `@ParametersAreNullableByDefault`, `@ReturnValuesAreNonnullByDefault`).

Using these annotations a programmer can declare how the code is meant to behave, and static code analysis (like e.g. _FindBugs_) can be used to verify that this is actually true. Also these annotations help others understanding code more easily, e.g. if confrontend with an annotated interface the necessity for null checks can easily be deducted from the annotations.

The Jsr305AnnotationsCheck supports enforcing the following code style:

1. Every method declaration, implementation or lambda requires nullness annotations for all parameters and return values except for primitive types (because a `void` or an `int` can never be null anyway).
2. The annotation can be made directly or applied through either inheritance from an already annotated class or a annotation for class-wide defaults.
3. Annotations need to make sense. For instance, a class-scope annotation cannot be used for a method, and a method annotation cannot be used for a class. 
4. In overridden methods, the following rule applies (regardless of what was annotated in the parent method): For parameter definitions `@Nonnull` annotation is always illegal because being less "nullable" cannot be assumed for a parameter in an inherited method. Conversely `@Nullable` is always allowed. For return values it is the other way round: `@CheckForNull` is always illegal while `@Nonnull` is always legal. 

Here are a few examples:
```
// no class-level annotation
class Class1 {
    @CheckForNull // Error: obj2 not annotated!
    String method1(@Nullable Object obj1, Object obj2) { ... }
    // Error: return value not annotated
    String method2() { ... }
}

// with class-level defaults
@ParametersAreNonnullByDefault
class Class2 {
    @CheckForNull // Legal
    String method1(Object obj1, Object obj2) { ... }
    @Nonnull // Legal
    String method2(Object obj1, @Nullable Object obj2) { ... }
    @Nonnull // Error, redefinition of obj2's nullness
    String method3(Object obj1, @Nonnull Object obj2) { ... }
    // Error: return value not annotated
    String method4() { ... }
}

// annotations apply across inheritance
@ParametersAreNonnullByDefault
interface Interface1 {
    @Nonnull
    Object method1(Object obj1, Object obj2);
    @CheckForNull
    Object method2(@Nullable Object obj1, Object obj2);
    @Nonnull
    Object method3(@Nullable Object obj1, Object obj2);
    @Nonnull
    Object method4(@Nullable Object obj1, Object obj2);
    @Nonnull
    Object method5();
}
class Class3 implements Interface1 {
    @Override // Legal
    public Object method1(Object obj1, Object obj2) { ... }
    @Override 
    @Nonnull // Legal, return value becomes less "nullable"
    public Object method2(Object obj1, Object obj2) { ... }
    @Override // Error: Setting a parameter to non-null in an overridden method is illegal
    public Object method3(@Nonnull Object obj1, Object obj2) { ... }
    @Override // Legal: parameter obj2 becomes more "nullable"
    public Object method4(Object obj1, @Nullable Object obj2) { ... }
    @Override 
    @CheckForNull // Error: return value becomes more "nullable"
    public Object method5() { ... }
}
```

The rules for treating inherited methods' return values and parameters can be relaxed, which can be useful for transitional periods when introducing this check to existing code. Having set the properties `allowOverridingReturnValue` and `allowOverridingParameter` to `true`, in the example above all method definititions for `Class3` will be legal.

To get a fuller picture of the possible warnings and the corresponding code, I have appended the test classes from the check's unit test (they are also in the PR). This is the output the check generates for them:

```
ParameterTestObject.java:35:44: No nullness Annotation for parameter definition found!
ParameterTestObject.java:40:45: No nullness Annotation for parameter definition found!
ParameterTestObject.java:40:64: No nullness Annotation for parameter definition found!
ParameterTestObject.java:73:41: Parameter definitions dont need checking, use @Nullable or @Nonnull.
ParameterTestObject.java:79:27: It is not allowed to increase nullness constraint for overriden method parameter definitions!
ParameterTestObject.java:97:35: @Nonnull and @Nullable are not allowed together!
PrimitivesTestObject.java:29:37: Primitives must not have any nullness annotations!
PrimitivesTestObject.java:34:38: Primitives must not have any nullness annotations!
PrimitivesTestObject.java:39:42: Parameter definitions dont need checking, use @Nullable or @Nonnull.
PrimitivesTestObject.java:44:5: Primitives must not have any nullness annotations!
PrimitivesTestObject.java:50:5: Primitives must not have any nullness annotations!
PrimitivesTestObject.java:56:5: @Nullable is not allowed on method return values!
PrimitivesTestObject.java:62:5: Primitives must not have any nullness annotations!
PrimitivesTestObject.java:69:5: Primitives must not have any nullness annotations!
PrimitivesTestObject.java:116:34: Primitives must not have any nullness annotations!
ClassTestObject.java:33:5: @ParametersAreNullableByDefault and @ParametersAreNonnullByDefault are not allowed together!
ClassTestObject.java:47:26: It is not necessary to annotate @Nullable if you annoted the method or class with @ParametersAreNullableByDefault.
ClassTestObject.java:57:29: No nullness Annotation for parameter definition found!
ClassTestObject.java:79:32: It is not necessary to annotate @Nonnull if you annotated the method or class with @ParametersAreNonnullByDefault.
ClassTestObject.java:87:36: No nullness Annotation for parameter definition found!
ClassTestObject.java:141:43: No nullness Annotation for parameter definition found!
ClassTestObject.java:148:9: It is not necessary to annotate @Nonnull if you annoted the class with @ReturnValuesAreNonnullByDefault.
ClassTestObject.java:152:9: @ReturnValuesAreNonnullByDefault is not allowed on method return values!
ClassTestObject.java:163:9: It is not necessary to annotate @Nonnull if you annoted the class with @ReturnValuesAreNonnullByDefault.
ClassTestObject.java:169:9: @ReturnValuesAreNonnullByDefault is not allowed on method return values!
ClassTestObject.java:187:9: @ReturnValuesAreNonnullByDefault is not allowed on method return values!
EnumTestObject.java:45:32: It is not necessary to annotate @Nonnull if you annotated the method or class with @ParametersAreNonnullByDefault.
EnumTestObject.java:54:36: No nullness Annotation for parameter definition found!
EnumTestObject.java:71:9: It is not necessary to annotate @Nonnull if you annoted the class with @ReturnValuesAreNonnullByDefault.
EnumTestObject.java:77:9: @ReturnValuesAreNonnullByDefault is not allowed on method return values!
EnumTestObject.java:90:5: @ParametersAreNullableByDefault and @ParametersAreNonnullByDefault are not allowed together!
InheritanceTestObject.java:47:47: No nullness Annotation for parameter definition found!
InheritanceTestObject.java:76:43: No nullness Annotation for parameter definition found!
DefaultParameterTestObject.java:37:5: It is not necessary to annotate @Nonnull if you annoted the class with @ReturnValuesAreNonnullByDefault.
LambdaTestObject.java:35:10: It is not allowed to increase nullness constraint for overriden method parameter definitions!
```
[jsr305-test-files.zip](https://github.com/sevntu-checkstyle/sevntu.checkstyle/files/2944684/jsr305-test-files.zip)

**Comment by mbert** [comment] 2019-04-02 12:58
Existing PR is here: https://github.com/sevntu-checkstyle/sevntu.checkstyle/pull/728
I may have to re-upload it (don't know the exact workflow here).

**Comment by romani** [comment] 2019-04-07 05:22
@rnveach, I am ok to host such Check in our project.
I am ok even with names.

Please review and approve issue, to start PR acceptance process.

**Comment by rnveach** [comment] 2019-04-07 09:31
My only concern is if this check might be doing too much in 1 place and if it could be broken up somehow. PR code is 1000 lines.

@romani Please confirm if you want these changes applied to sevntu and checkstyle code.

**Comment by romani** [comment] 2019-04-08 04:05
>Please confirm if you want these changes applied to sevntu and checkstyle code.

We should run it with ignore severity. We are not ready to use that approach in design.

>Also what package should this check be in? 

I would avoid extra packages. I think better place is coding package

**Comment by mbert** [comment] 2019-04-08 06:42
I'm fine with that. I will prepare a new PR with the code living in the coding package. Since I already have feedback from the CI I'll also look into the test coverage wich was still a bit too low.

**Comment by romani** [comment] 2019-04-11 12:19
Oh, yes, we know, in main project we demand even mutation 100%, so in sevntu we are relaxed a bit. 
Note for you: coverage should be done by Input files. Only most exceptional cases should be covered by mocks and reflection. We allow reflection to avoid damage of design but it last resort.
Easy way to find all required input file is to substitute expression with some value and run our regression diff tool on a lot of sourses, found diff copy to inputs

**Comment by rnveach** [comment] 2019-04-11 12:24
Since this is sevntu, he has limited regression support since groovy doesn't support sevntu.
See https://github.com/checkstyle/contribution/tree/master/checkstyle-tester#testing-sevntu-checks and https://github.com/checkstyle/contribution/issues/340

**Comment by mbert** [comment] 2019-04-11 12:25
Thank you. I have finished pimping the tests. The vast majority is on input files, but I have also implemented some classic unit tests.

**Comment by mbert** [comment] 2019-04-11 12:26
Yes, I've read that part about checkstyle-tester. I haven't really started yet. If you've got any additional information that could speed up the process this would help a lot.

**Comment by rnveach** [comment] 2019-04-11 12:28
@mbert If you need additional help, just point out what you need the PR and we will try to help as best we can.

**Comment by mbert** [comment] 2019-04-11 12:38
I will try to get a run with the checkstyle-tester today or tomorrow (depends on project load here). 
If I run into problems, I'll ask here. 

I have also created an example project that I would upload to this issue. It is annotated the way we want to enforce it with the plugin, also it uses the sevntu maven plugin from a preceding "mvn clean install" with the fresh code. 

Once I have finished with the checkstyle-tester and found that no more amendmends to the code seem necessary from my side I'll upload the PR and the sample project. Sounds OK?

**Comment by rnveach** [comment] 2019-04-11 15:51
sounds fine to me.

**Comment by mbert** [comment] 2019-04-12 08:13
I don't seem to understand how to run the checkstyle-tester correctly. I'm running it like this: 

`groovy diff.groovy --localGitRepo /home/md/src/checkstyle --patchBranch master --config my_check.xml --listOfProjects projects-to-test-on.properties
`

I edited `my_check.xml` and added the new check's configuration. The script starts up fine, but after a while emits an error message:

```
Starting diff report generation ...
patch-diff-report-tool execution started.
Exception in thread "main" java.lang.IllegalArgumentException: Both Base and Patch XML report files have the same path.
```

According to the docs (_"Sevntu can only be run with patch only branch and config."_) I am using only a patch branch and a config argument - which seems to make sense because there's nothing to diff against when there are no changes in the `checkstyle` base project. 

Can you give me a quick hint how to run this properly?

**Comment by mbert** [comment] 2019-04-12 11:38
OK, I've (kind of) helped myself now by creating a branch in the checkstyle repo which is identical to `master`. Here's the results I obtained. 

In the _index.html_ file there are lots of warnings emitted by the new check which is to be expected of course. So that result seems fine, right? 

[report.zip](https://github.com/sevntu-checkstyle/sevntu.checkstyle/files/3073065/report.zip)

**Comment by mbert** [comment] 2019-04-12 11:59
Here's an annotated example project. To try out the new check, the following steps are required:

1. Cherry-pick the commit from my PR #742 
2. In the _sevntu-checkstyle_ workspace, run `mvn clean install` in both, _sevntu-checks_ and _sevntu-checkstyle-maven-plugin_
3. Unzip the attached archive [example-webservice.zip](https://github.com/sevntu-checkstyle/sevntu.checkstyle/files/3073125/example-webservice.zip) with the example project
4. Run `mvn clean verify` to build the project, this should not generate any checkstyle warnings
5. Play around with some of the sources (e.g. remove, add or change existing nullness annotations) and run `mvn checkstyle:check` to see what changes

**Comment by mbert** [comment] 2019-04-12 12:11
Now I've got the first CI feedback. That was a new one to me.

There's a number of PMD failures, most of them however on the 'test object' java files used by the unit test (i.e. code that is never executed). Would excluding them from the check be acceptable? If yes, how?

**Comment by rnveach** [comment] 2019-04-12 15:58
@mbert Anything related to the implementation, lets discuss in the PR so we don't have 2 split conversations going on.

> of them however on the 'test object' java files used by the unit test (i.e. code that is never executed). Would excluding them from the check be acceptable? 

If your files are input files to tests, they should go under `test/resources` and be prefixed with the words `Input`. We expect violations on pure tests or main code to be resolved or suppressed with a reason.

> I'm running it like this:
groovy diff.groovy --localGitRepo /home/md/src/checkstyle --patchBranch master --config my_check.xml --listOfProjects projects-to-test-on.properties 

It must be `--patchConfig` and not `--config`. See examples in readme.

**Comment by mbert** [comment] 2019-04-12 16:16
> If your files are input files to tests, they should go under `test/resources` and be prefixed with the words `Input`. We expect violations on pure tests or main code to be resolved or suppressed with a reason.

Ah, good to know. Will fix that next Monday. And then let's see what remains. 

> It must be --patchConfig and not --config. See examples in readme.

Also good to know. Is the result I have produced using my little workaround relevant, or should I rerun it?

**Comment by rnveach** [comment] 2019-04-12 17:14
> Here's the results I obtained: report.zip

It looks you just gave us the results of what is in the patch directory. When groovy is done, there is a directory named `diff` that should have the projects and HTML files which are more user friendly to view.

**Comment by mbert** [comment] 2019-04-15 08:19
OK, here's what's in the `diff` folder: [diff.zip](https://github.com/sevntu-checkstyle/sevntu.checkstyle/files/3079093/diff.zip)

**Comment by rnveach** [comment] 2019-04-15 10:53
@mbert Again lets move this discussion on regression to the PR.

**Comment by vovkab** [comment] 2019-04-15 18:57
Probably it's a bit late, but as it was mentioned in original post there is whole bunch of different nullability annotations out there, i.e. jsr305, jetbrains, android, androidx and probably more.

Maybe it would make sense to create more generic check, for example `RequireAnnotation` with some level of configurability, i.e. which annotations are required on which fields or return methods and etc?

For example, to enforce presence of one of the nullability annotations for each object we could do something like:

```
<module name="RequireAnnotation">
  <property name="oneOf" value="androidx.annotation.Nullable, androidx.annotation.NonNull"/>
  <property name="tokens" value="VARIABLE_DEF, PARAMETER_DEF, CTOR_DEF,"/>
  <property name="ignorePrimitiveTypes" value="true"/>
 </module>
```

With some validation options:
`oneOf` – validates the value against exactly one of the annotations
`allOf` – validates the value against all the annotations
`anyOf` – validates the value against any (one or more) of the annotations

Or it still not generic enough and would not get much usage outside of the nullability annotations, what do you think?

**Comment by mbert** [comment] 2019-04-15 19:02
The existing check does not require a particular implementation of those annotations. It uses a superset of the most commonly used annotation names. That works pretty well.

What you propose would be another, more restricitve, approach. Since this issue is all about adding the existing implementation to sevntu in order to make it more easily accessible for people, I cannot really propose anything different from what is already there.

**Comment by vovkab** [comment] 2019-04-15 19:05
@mbert so it's also is going to work with other annotations, i.e. android, jetbrains and etc?

**Comment by mbert** [comment] 2019-04-15 19:07
I would expect so. You can easily try that out yourself by using the existing, independent plugin: https://github.com/bjrke/JSR305CheckstylePlugin/

**Comment by vovkab** [comment] 2019-04-15 19:41
Great, thanks.

**Comment by vovkab** [comment] 2019-04-15 20:37
@mbert looks like it doesn't work for android annotations, which are a bit different from jsr305. For example, Android non-null annotation is `@NonNull`, while jsr305 is `@Nonnull`

Also, I've noticed that it complains:

```
@Nullable is not allowed on method return values!
```

Any reason why method can't return `null`, or does it expect to be annotated with `@CheckForNull`?

Here is more information about androids annotations:

```
@Documented
@Retention(CLASS)
@Target({METHOD, PARAMETER, FIELD, LOCAL_VARIABLE, ANNOTATION_TYPE, PACKAGE})
public @interface Nullable {}
```

https://developer.android.com/reference/android/support/annotation/Nullable

```
@Documented
@Retention(CLASS)
@Target({METHOD, PARAMETER, FIELD, LOCAL_VARIABLE, ANNOTATION_TYPE, PACKAGE})
public @interface NonNull {}
```

https://developer.android.com/reference/android/support/annotation/NonNull

Would be really great if we could also use this plugin for android too.

**Comment by mbert** [comment] 2019-04-15 20:48
> @mbert looks like it doesn't work for android annotations, which are a bit different from jsr305. For example, Android non-null annotation is `@NonNull`, while jsr305 is `@Nonnull`

I'm sure that support for `@NonnNull` can be added (if it is semantically similar to `@Nonnull`).

> Also, I've noticed that it complains:
> 
> ```
> @Nullable is not allowed on method return values!
> ```
> 
> Any reason why method can't return `null`, or does it expect to be annotated with `@CheckForNull`?

Exactly. Return values need to be annotated `@CheckForNull` if they can return `null`.

> Would be really great if we could also use this plugin for android too.

I agree that this would make lots of sense. But let's for now get the existing plugin into sevntu which is already quite a task. I had a chat with the main developer of the existing plugin recently, and we both agree that once the code is in sevntu it should be maintained further as part of the sevntu project. That would pretty likely lead to a larger circle of users and hence additional ideas for improvements (and hopefully also PRs).

**Comment by romani** [comment] 2019-04-16 13:25
>here's what's in the diff folder

Please share by GitHub.io as suggested in  readme for tool, it would speedups review.

**Comment by mbert** [comment] 2019-04-16 14:17
> Please share by GitHub.io as suggested in readme for tool, it would speedups review.

I have already shared it as a zip file in a [comment under the PR](https://github.com/sevntu-checkstyle/sevntu.checkstyle/pull/742#issuecomment-483561785). 

It has now also been added to the site: https://mbert.github.io/sevntu.checkstyle/reports/example-webservice-diff/index.html

**Comment by romani** [comment] 2019-04-17 01:02
Please recheck that you shared all files.
https://mbert.github.io/sevntu.checkstyle/reports/example-webservice-diff/example-webservice/xref/home/md/src/contribution/checkstyle-tester/repositories/example-webservice/src/main/java/org/example/webservice/service/impl/PingServiceImpl.java.html#L79 gives error.

I noticed only one project, please run check on all projects that we have in config, it will not find violation but at we can be somehow sure that Check is not crashing.

Do you have some open source projects in mind that use such annotations? Maybe this https://checkerframework.org ? Probably search at GitHub by annotation name can lead you some open source project

**Comment by rnveach** [comment] 2019-04-17 01:09
@romani regression discussion was moved to PR. That is where links to all projects is located.

**Comment by romani** [comment] 2019-06-19 03:24
fix is merged

**Closed by romani** 2019-06-19 03:24 UTC
Labels: approved, new module
